image: gradle:alpine

default:
  tags:
    - shelllocal

stages:
  - test
  - report
  - deploy

test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew clean test
  artifacts:
    paths:
      - build/allure-results/*
  rules:
    - when: always

report:
  stage: report
  script:
    - ./gradlew allureReport
    - echo "Allure report live here - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/build/reports/allure-report/allureReport/index.html"
  artifacts:
    paths:
      - ./reports/allure-report/allureReport/*
  rules:
    - when: always

deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r ./reports/allure-report/allureReport/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always